# *******************************************************************
# * Tesikaga Art - Main Settings
# * This is the primary file for configuring the simulation and hardware.
# *******************************************************************

# Serial port for the Arduino
# Mac: /dev/tty.usbmodemXXXX or /dev/tty.usbserial-XXXX
# Linux: /dev/ttyACM0 or /dev/ttyUSB0
# Windows: COM3
serial_port: "/dev/ttyACM1"
baud_rate: 921600

# --- Visual & Simulation Parameters ---
# Screen dimensions for the simulation window
view_width: 800
view_height: 800

# The width and height of the pond area in the physical model (in meters)
model_width: 5.3   # 池の幅（短辺）
model_height: 6.3  # 池の高さ（長辺）

# --- Hardware & Layout ---
# Name of the LED position file in assets/data/
led_layout_file: "led_positions_4_segments.csv"
# Total number of physical LEDs in the full installation
num_leds: 1200

# --- Hardware Test Mode ---
# When true, main_real.py will only use a subset of LEDs for testing.
# This allows you to test with a shorter strip without changing the main num_leds.
enable_test_mode: false
test_strip_led_count: 1200 # Number of LEDs on your physical test strip

# ===================================================================
# === INPUT SOURCE CONFIGURATION
# ===================================================================
# "mouse" または "udp" を指定
input_source_type: "udp" 

# UDPを使用する場合の設定
udp_settings:
  host: "127.0.0.1"
  port: 9999

# --- Automatic Human Movement (for testing without a real input) ---
# If enabled, this will override the 'input_source_type' and generate
# a fake human moving in a pattern.
auto_human_movement:
  enabled: false
  # Pattern type: "circle" or "patrol" (patrol moves between two points)
  pattern: "circle" 
  speed: 0.2 # meters per second
  radius: 2.4 # for circle pattern
  size: 15.0 # size of the auto-human


 # LiDARの姿勢情報ファイルへのパス (プロジェクトルートからの相対パス)
transform_matrix_path: "config/calibration_result.yaml"


# --- AI & Visual Tuning ---
# Fine-tuning parameters for bird behavior and simulation visuals.
ai_tuning:
  chirp_probability_per_frame: 0.005
  min_brightness_falloff: 0.4 # 40% brightness guarantee for falloff

# --- Simulation Cast ---
# List of bird IDs to include in the simulation.
# Names must match the keys in config/config_structure.py
# You can repeat names to have multiple birds of the same species.
birds_to_simulate:
  - ojirowasi
  - shimafukuro
  - tancho
  - oohakucho
  - ooluri
  - kumagera
  - nogoma
  - benimashiko
  - ojirowasi
  - shimafukuro
  - tancho
  - oohakucho
  - ooluri
  - kumagera
  - nogoma
  - benimashiko
  


# --- ★鳥の全体的な輝度設定 (0.0から1.0) ---
global_brightness: 0.8

# ===================================================================
# === SIMULATOR VISUALS CONFIGURATION
# ===================================================================
# このセクションは、シミュレーター画面上の見た目のみに影響します。
# 物理的なLEDの色や明るさには一切影響を与えません。
simulator_visuals:
  ooluri:
    base_color: [50, 150, 255]   # 鮮やかな青
    accent_color: [255, 255, 255] # 白
  oohakucho:
    base_color: [255, 255, 255] # 白
    accent_color: [255, 220, 0]   # 黄色
  ojirowasi:
    base_color: [173, 216, 230] # ライトブルー
    accent_color: [255, 215, 0]   # 金色
  shimafukuro:
    base_color: [0, 100, 0]      # ダークグリーン
    accent_color: [0, 0, 139]      # ダークブルー
  kumagera:
    base_color: [20, 20, 20]      # ほぼ黒
    accent_color: [220, 20, 60]    # ダークレッド（クリムゾン）
  tancho:
    base_color: [255, 255, 255] # 白
    accent_color: [220, 20, 60]    # 赤
  nogoma:
    base_color: [139, 69, 19]     # ブラウン (サドルブラウン)
    accent_color: [255, 140, 0]    # オレンジ
  benimashiko:
    base_color: [210, 180, 140] # ブラウン (タン)
    accent_color: [255, 182, 193] # ピンク